# Site settings
copyright: {{ 'now' | date: "%Y" }} Lijiaqi
url: https://lijiaqi-github.github.io/beacon/
baseurl: /beacon
title: Beacon
tagline: by HTML5 UP
description: "Just another fine responsive site template designed by HTML5 UP<br>and released for free under the Creative Commons."
contactTagline: none
# Contact
address: "12345 Somewhere Road 654<br>Nashville, TN 00000-0000<br>USA"
email: name@provider.com
phone: (012) 345-6789
twitter: username
facebook: username
github: username
instagram: username
linkedin: username

# Featurette -- leave values blank if you do not want them to appear
featuretteTitle: A
featuretteTagline: Ac
featuretteLink: /elements.html

feature1Title: title1
feature1Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature1Icon: icon major fa-code
feature1Url: "https://gemini.google.com/app?hl=ja" 

feature2Title: title2
feature2Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature2Icon: icon major fa-lock

feature3Title: title3
feature3Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature3Icon: icon major fa-cog

feature4Title: title4
feature4Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature4Icon: icon major fa-desktop

feature5Title: title5
feature5Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature5Icon: icon major fa-chain

feature6Title: title6
feature6Tagline: Phasellus convallis elit id ullam corper amet et pulvinar. Duis aliquam turpis mauris, sed ultricies erat dapibus.
feature6Icon: icon major fa-diamond
