# Site settings
copyright: 2025 Lijiaqi
url: https://lijiaqi-github.github.io/beacon/
baseurl: /beacon
title: Beacon
tagline: by HTML5 UP
description: "Just another fine responsive site template designed by HTML5 UP<br>and released for free under the Creative Commons."
contactTagline: none


# Featurette -- leave values blank if you do not want them to appear
featuretteTitle: A
featuretteTagline: Ac
featuretteLink: /elements.html

feature1Title: title1
feature1Tagline: x
feature1Icon: icon major fa-code
feature1Url: "https://gemini.google.com/app?hl=ja" 

feature2Title: title2
feature2Tagline: c
feature2Icon: icon major fa-lock

feature3Title: title3
feature3Tagline: v
feature3Icon: icon major fa-cog

feature4Title: title4
feature4Tagline: P
feature4Icon: icon major fa-desktop

feature5Title: title5
feature5Tagline: e
feature5Icon: icon major fa-chain

feature6Title: title6
feature6Tagline: q
feature6Icon: icon major fa-diamond

feature7Title: title7
feature7Tagline: t7c
feature7Icon: icon major fa-diamond
